### ISSUE TITLE
Future of ns3/cp3

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#101]
The $50 credit promo at Vultr we had expired on 26 February, so the $5 credit that @labster donated is the only that's still in the account.

We currently have $3.49 credit left, and if we cancel ns3 now we only lose $0.99 of the credit.

If we do not cancel ns3, we have to put funds there. @labster @JohnFLewis please advise about the future of ns3.

**Comment by JohnFLewis** [comment]
From a DNS standpoint - no comment. Two NS servers distributed physically apart are fine. The fact we use cloud providers is an issue as it means our DNS is located with only one provider, as such it is not optimal yet not harmful or risky.

**Comment by Southparkfan** [comment]
In any case I do not want ns3 back as a cache proxy. I think using it for DNS is not needed either.

Vultr looks nice, but it's also quite expensive compared to RamNode, and

**Comment by JohnFLewis** [comment]
Fine by me but the server has to be removed from namecheap DNS at least 24-48 hours before the server is powered off.

**Comment by Southparkfan** [comment]
Problem we also have is that some custom domains have ns3 configured.

Is it fine if we point ns3.mh.o to ns2 IP? It's not the best solution, but it's the only one we have.

**Comment by JohnFLewis** [comment]
I guess it is fine. This is why it's awkward in theses cases. If you decide you want to run 3 nameservers, you must run three nameservers. It's also slightly unfair though as ns1 will get 33% of traffic while ns2 gets 67% of traffic.

**Comment by labster** [comment]
Poor ns2.  I'm OK if you want to shut down ns3.

But I still want you to choose some provider that is not RamNode for a backup server.

**Comment by JohnFLewis** [comment]
Agreement: it will die.
