### ISSUE TITLE
[Decom] Remove ns3 from DNS

### ISSUE THREAD

**Issue by JohnFLewis** [miraheze/puppet#102]
ns3 needs to be removed from DNS globally for miraheze and then a short stop put in place for the old ns3.mh.o remnants (bad, I'll look at the best feasible way for it I guess).

**Comment by JohnFLewis** [comment]
Removed from DNS as NS records.

**Comment by JohnFLewis** [comment]
Can't remove from the Namecheap domain. According to Namecheap I don't have permission to edit the domain @Southparkfan

**Comment by JohnFLewis** [comment]
Once done and the 24 hours is up (confirmed by propagation) the server can be shutdown.

**Comment by Southparkfan** [comment]
Removed.

**Comment by JohnFLewis** [comment]
Let the 24 hour/propagation period start!

**Comment by JohnFLewis** [comment]
Seems all DNS servers have flushed ns3 (which is surprisingly quick!). So I guess network monitoring is our friend for now.

**Comment by JohnFLewis** [comment]
It is dead.
