### ISSUE TITLE
Wipe logs containing PII after 90 days

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#114]
Do you love privacy if you store access logs for longer than 90 days?
```
185.52.1.76 - - [02/Aug/2015:14:40:32 -0400] "GET / HTTP/1.1" 200 11104 "-" "check_http/v2.1.1 (monitoring-plugins 2.1.1)"
```

We should ensure that all logs containing PII (MediaWiki logs, access logs, etc) are completely wiped forever after 90 days, using logrotate.

- [x] Apache access logs - seems to be already done
- [x] /var/log/mediawiki/* - seems to be already done
- [x] NGINX access logs

**Comment by JohnFLewis** [comment]
Log rotation. The base should exist - just modify it.

**Comment by JohnFLewis** [comment]
Giving to SPF as it seems just NGINX has no log rotation at all in puppet and nginx is his area.

**Comment by JohnFLewis** [comment]
All NGINX logs are now removed after 84 days (https://git.io/vadiA) as opposed to nginx's default of 365 days.
