### ISSUE TITLE
Disaster recovery plan

### ISSUE THREAD

**Issue by NDKilla** [miraheze/puppet#115]
Per #48, SPF's comment, and other concerns about backups, I think we should start to draft a disaster recovery plan. I think this should include most if not all of the following, and probably more I'm not thinking of at the moment:

- [x] - Dedicated server for backups, preferably not at the same host or physical location as any of our current servers. See issue #48 
- [x] - Automated system of backups? Possibly cron job xml dumps of wikis and rsync/cp to remote server. See issue #48
- [x] - Frequent and public discussion of current server usage, security, and costs.
- [x] - Discussion of privately stored data and how it is handled. What to do to notify users / prevent further problems if a server containing private / identifiable information is compromised. This should include a finalized privacy policy, but it should also be documented off-wiki.
- [x] - Document (on and off wiki) how to set up various servers and how we could restart Miraheze on new servers / host if issues outside of our control prevent continuing our current path.
- [x] - Off-wiki documentation of finances. @labster 

Edited the checklist for private data to include mention of privacy policy.

**Comment by JohnFLewis** [comment]
Cron backups via maintenance scripts - bad. You'd want a fair memory use script regularly handling the work not poorly crafted maintenance scripts.

Elaborate point 3.

4 this would include full mysql backups, now that's a whole can of worms.

Puppet does all that stuff! If you have to document thing manually like how to set up a server, you've not done puppet right at all.

**Comment by NDKilla** [comment]
@JohnFLewis Noted, we'd have to come up with something else.

I mean that server costs are occasionally discussed on IRC (mostly when upgrading servers) but these things should be openly discussed more often. For server usage, current tech namespace docs seem good enough.

I get full mysql backups would include private data, but I'm not exactly sure how that was relevant to that checkmark specifically.

In that case (which I assumed anyways) how to get puppet working on a brand new server should be documented

**Comment by JohnFLewis** [comment]
Cost really is not a major public interest thing - in fact we discuss cost more than most other projects do. We shouldn't be setting a goal to plaster the cost of everything everywhere, we disclose Publically what servers are, cost is there, we discuss what upgrades are, cost is there, we even at times discuss our yearly cost, it's there. We discuss things fluidly - I dont want to force us to discuss cost rigidly.

Well mysql dumps are more or less the only private thing we'd be backing up. The whole checkbox is mysql dumps.

It is docmented! its even documented in the readme. Literally 'apt-ge install puppet' and run puppet. Bam, it's working.

**Comment by labster** [comment]
> Frequent and public discussion of current server usage, security, and costs.

I'm not sure what you want by discussion.  In terms of usage, we have ganglia public, and Category:Servers lists our electronic assets.  This is actually a good deal more public than most orgs.  Security: mostly auditable by looking at our puppet, so already mostly public.  Costs: Already more public than most nonprofit orgs by having a running balance on the Finance page.

If you're asking for public discussion of which direction we should be taking on these things -- no.  Or at least no more than we already do.  45% of business happens in IRC in a public logged channel, and another 50% here on Github.  If you care, you're already keeping track of these places.  We do not need to invite the general public to come in and bikeshed, because if they care they're already involved.

> Off-wiki documentation of finances. @labster
So wait, are you asking for the some of the books to be kept secret?  Or an occasional `wget 'https://meta.miraheze.org/wiki/Finance'`?

**Comment by NDKilla** [comment]
> 45% of business happens in IRC in a public logged channel

Is the link to the logs anywhere except the #miraheze topic? Might be nice to post it on wiki somewhere.

> So wait, are you asking for the some of the books to be kept secret? Or an occasional wget 'https://meta.miraheze.org/wiki/Finance'?

I don't mean keep anything secret. I mean if the site goes down, the databases get destroyed or compromised etc, it would be nice to still have a record.

**Comment by labster** [comment]
> Is the link to the logs anywhere except the #miraheze topic? Might be nice to post it on wiki somewhere.

:white_check_mark: Done

**Comment by JohnFLewis** [comment]
Hate issue lists. Anyway:

Marked off-wiki finances as done (paypal, lobster's memory - which ever way, it's not just on-wiki).

Puppet is straight forward so the 'how to set things up on a new server' is done. Obviously if db1 goes, there's no point as all the data is on it. Private git is backed up on every single server and it's not really static - it can all be changed.

Frequent discussion of thing is marked as done as, well was this ever a goal to achieve? What happens, happens. Everything can be audited (via puppet if you believe it!) and we can't force people to discuss if db1 is still needed anymore, can we? I mean - we can but it won't change anything :)

The 'discussion of private data' is an oxymoron. Like, why would you discuss what private data is, its private :) - the 'what to do is x or y is compromised, who to tell, what to say and so on' is something I'll do now.

I like to add humour.

**Comment by JohnFLewis** [comment]
https://meta.miraheze.org/wiki/Tech:Compromised_Handling

**Comment by JohnFLewis** [comment]
Hardly a disaster recovery plan for seemingly when the backup issue is resolved, this is resolved now? That seems weird.

**Comment by NDKilla** [comment]
So I failfish? Check off the last two things when they're done (soon(TM)?)

> https://meta.miraheze.org/wiki/Tech:Compromised_Handling

I read this and seems.. okay.. except for the fact that it more or less says "figure out how the password was compromised" or "notify operations" over and over. If mw* get's compromised I can just shut it down Kappa

**Comment by Southparkfan** [comment]
Disaster recovery, crash recovery, compromised handling, .....?
