### ISSUE TITLE
An issue asking for mediawiki-admins

### ISSUE THREAD

**Issue by labster** [miraheze/puppet#119]
Apparently I should be asking for this.

**Comment by JohnFLewis** [comment]
A SSH key would be super super super useful!

@Southparkfan just give a yes here.

**Comment by Southparkfan** [comment]
Approved.

**Comment by labster** [comment]
brent@ragnar ~/.ssh> cat id_rsa.pub
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMIFCaagRn4CCVDfuixkOdeYw4+Jdy3mg01SWLJ7F3nQKKVhSNlnKZrsiWsI6ihj6K06QBQxrFB3AfaqpWqALitkI+5CisnwOfutAGZu9+cbE8qo9sDAmm34N52yfnzmcFx2kgj0BDL/T+C/iiG8ZRdmeKes4Lv5OylDo+f0sHdbzc3YTTeuTafwgrXUeHv3FCrpw/xu0t9Vgawt6HACVSYq2+fglY+4oG4Pc1+hBGnRPyet+dILYTHmDem1iG2vCajiTbtnN+gKdWp3+2CeZ7YLRDexm3ncoKLPXi+nxTp6qKknH0QOd52YOnNRj3TGuif7mrRn+LVMFLaMhxuUst blaabs@perceptyx.com

**Comment by JohnFLewis** [comment]
Notice: /Stage[main]/Users/Users::Hashuser[labster]/Users::User[labster]/User[labster]/ensure: created
