### ISSUE TITLE
Phabricator migration

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#125]
The migration to https://phabricator.miraheze.org will be soon!

- [x] Migration of data [mixed]
 - [x] Write working GitHub -> Phabricator script [@Southparkfan]
 - [x] GitHub issues (puppet/mw-config/CreateWiki/dns) [@Southparkfan]
 - [ ] Feature Requests [@NDKilla @Reception123] [blocked by non-working OAuth login]
- [x] Interface [@Southparkfan]
 - [x] Dashboards [@Southparkfan]
 - [x] Forms (normal task/Security Issue/CSR Request/Feature Request/etc) [@Southparkfan]
- [ ] Technical [@Southparkfan]
 - [x] /srv/phab/phabricator/conf/local/local.json backup [@Southparkfan]
 - [x] Backup of any customizations (spaces/view policies) [@Southparkfan]
 - [x] Final implementation (wipe DB, final import of GitHub data) [@Southparkfan]
 - [ ] Working MediaWiki OAuth login [@Southparkfan] [blocked by: https://phabricator.wikimedia.org/T132842]
- [x] Puppetization [mostly @JohnFLewis]
 - [x] Apache [@Southparkfan]
 - [x] Git directories [@JohnFLewis]
 - [x] MySQL grants [@JohnFLewis]
 - [x] /srv/phab/repos [@Southparkfan]
- [x] Blockers?
 - [x] Approval of misc2? [@JohnFLewis and @labster]
 - [x] Be ensured everyone registers?
 - [x] Any wishes?

**Comment by JohnFLewis** [comment]
Done.

**Comment by JohnFLewis** [comment]
I intend on having security AT miraheze.org and a csr AT miraheze.org being directed to Phabricator with the intent of allowing security issues and CSR requests be literally an email away from people in case people don't want to the use the forms SPF's is making (plus an email-in security email is standard practise anyway, might as well hook it up to the task tracker).

**Comment by JohnFLewis** [comment]
I'm going to mark the 'backup local.json' thing as done as well its in git now. If that's not backed up, nothing is. Just needs an update and then to actually make it apply our version via a template.

**Comment by JohnFLewis** [comment]
Blockers checked off as they're not blockers anymore really.

Accounts can be created by an admin, so we don't require people to register. We don't need a misc2 for this. We don't have any wishes.

**Comment by Southparkfan** [comment]
Migration is going on.

**Comment by Southparkfan** [comment]
Migrated to https://phabricator.miraheze.org/T227.
