### ISSUE TITLE
Do not use GitHub issues for reporting issues!

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#130]
As of April 2016, we migrated from GitHub's issue tracking to Phabricator. If you want to file an issue, please visit https://phabricator.miraheze.org. You can register and login with your GitHub account.

**Comment by LegoFan4000** [comment]
Why not go into the settings tab and disable issues alltogether? @Southparkfan @JohnFLewis @NDKilla @NDKilla-public

**Comment by NDKilla-public** [comment]
@LegoFan4000 This issue provides a reason that issues are "disabled" and provides a link to our actual issue tracking, something we cannot do if it's disabled completely. I guess we could update the repo readme but meh.

**Comment by JohnFLewis** [comment]
Actually it's because we need old issues to still be readable because old links still exist.
