### ISSUE TITLE
Access request (mediawiki-admins for revi)

### ISSUE THREAD

**Issue by revi** [miraheze/puppet#15]
Per IRC discussion, making issue here.

**Comment by revi** [comment]
[Github<=>irc<=>miraheze account verification](https://meta.miraheze.org/w/index.php?diff=1375&oldid=1285&rcid=1793).

Above referenced commit has my ssh key, or [[meta:Ussr:Revi/ssh]]

**Comment by JohnFLewis** [comment]
No issues raised and the above is satisfactory enough for me. Will do shortly.

**Comment by JohnFLewis** [comment]
Notice: /Stage[main]/Users/Users::Hashuser[revi]/Users::User[revi]/User[revi]/ensure: created
