### ISSUE TITLE
check_http should check for status code too

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#23]
Miraheze is experiencing frequent 502 errors due to HHVM issues. It is important that we get notified when status codes other than 200/301/302 are returned when checking https://meta.miraheze.org/wiki/Miraheze.

This is high priority and should be done soon.

**Comment by revi** [comment]
Related: miraheze/mw-config#162

**Comment by JohnFLewis** [comment]
It does however we're checking http:// which never returns any other than 301.
