### ISSUE TITLE
Sudo errors

### ISSUE THREAD

**Issue by revi** [miraheze/puppet#24]
```
ssh revi@mw1.mh.o
sudo service HHVM restart
(First-time sudo password input message)
```

Never happened until yesterday. Something must be going wrong.

**Comment by revi** [comment]
IRC log suggests that this also happened to mutante  too.

**Comment by JohnFLewis** [comment]
revi@mw1:/home/johnflewis$ sudo service hhvm status
● hhvm.service - LSB: Starts The HHVM FastCGI Daemon

mutante@mw1:/home/johnflewis$ sudo service hhvm status
● hhvm.service - LSB: Starts The HHVM FastCGI Daemon

**Comment by JohnFLewis** [comment]
ah, reading the original comment originally again:

mutante@mw1:/home/johnflewis$ sudo service HHVM status
[sudo] password for mutante:

root@mw1:~# service HHVM status
● HHVM.service

Closing. You're trying to work with a non-existent service (and thus non-existent sudo rule).
