### ISSUE TITLE
Keep or delete SSH account for NDKilla?

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#32]
NDKilla notified me that he lost access to his computer/hard drive, so I immediately revoked his SSH key in c98876ceac1ad919bbe741c8700fada69420b63e as a security measure.
However, a few weeks later it seems that the account is still disabled.

NDKilla, do you want to keep your SSH account? I don't know if you have access to a secure computer, and if you are securely able to generate a new SSH key, but I'd like to know the status on this. Your SSH account is still on mw1 (just without no keys), so if you want me to upload a new key (provided that you can ensure this was safely done), then just ask. If you think you need a bit more time for that, then please say that so we're aware of that.

**Comment by JohnFLewis** [comment]
In theory it was never disabled, just key revoked (meaning it is still active). Seeing as there has been no finite end to this, please absent the account.

**Comment by Southparkfan** [comment]
User has been removed from the organization (and sysadmin global group) due to inactivity.
