### ISSUE TITLE
Miraheze RC not working/connect

### ISSUE THREAD

**Issue by Reception123** [miraheze/puppet#37]
I was/am kind of busy this month (i hope to be really active again soon) but I noticed that Miraheze RC hasn't worked for a long time, I'm not sure if it's down or no one booted it.

**Comment by Southparkfan** [comment]
Will restart it soon.

**Comment by Reception123** [comment]
Okay. I think this is really important, as we can use it to spot global vandalism.

**Comment by Southparkfan** [comment]
Up again.
