### ISSUE TITLE
private.revi.wiki ssl cert

### ISSUE THREAD

**Issue by revi** [miraheze/puppet#38]
~~basically a reminder to install it~~

**Comment by Southparkfan** [comment]
Hehe :p

**Comment by Southparkfan** [comment]
Will do this together with the RF requests.

**Comment by revi** [comment]
We have to move reviwiki's domain to the new ssl, and keep old url as a redirect, just for the record. And CentralAuth too.

**Comment by Southparkfan** [comment]
@revi I can't add new custom domains to Google's reCAPTCHA.

Can you do that for me? If you give me the private token/key I'll add it to mw-config.

**Comment by Southparkfan** [comment]
@revi: unfortunately I had no time anymore.

Tomorrow!

**Comment by Southparkfan** [comment]
Done.
