### ISSUE TITLE
NDKilla mediawiki-admins access request

### ISSUE THREAD

**Issue by NDKilla** [miraheze/puppet#40]
Hi all, NDKilla again.
Requesting access to mediawiki-admins again so that I can start to help out more again. I was a previous mediawiki-admin and know how to handle MediaWiki (and some related) things. I've had my access revoked due to extreme inactivity ( #32 ) but I've started to be more active on Meta Wiki and Test Wiki again, including handling a wiki request.

I'd like mediawiki-admin to resume/continue being able to handle feature requests, download/enable new extensions, and run maintenance scripts for wikis :)

Before being removed from the mediawiki-admin GH group and sysadmin on-wiki, my SSH key was revoked (as a 'security' measure). This was due to loss of ability to use my actual computer. I've had the HDD with my SSH key on it and I'd like to think I'm really cautious about things like this. I also have since my demotion enabled 2fa on my GH account.

**Comment by Southparkfan** [comment]
@NDKilla please upload your SSH key here.

**Comment by NDKilla** [comment]
---- BEGIN SSH2 PUBLIC KEY ----
Comment: "rsa-key-20151221"
AAAAB3NzaC1yc2EAAAABJQAAAQEA483LlTZ0FqGGJSKYHkQXSo7NUmmziIbb/KH9
NjwEO8YihLG2rAMh9L2C2LX4ggaSxSMlupopL3lXr8yG8FqVjX1fVofGEj9adGsg
48lhrbauYFQ9ZKK5AGuYHzyKkONOIpHio0eQ5z6GSZdnHOI22Idn7IEqghTnGDFb
8PVqf7fjiS2LIGhoZJWVkSFuxQNHpgX6OyqbsolE3sp8ZjfY4zX+KWqavs1LogWE
qNQNM3eUNN7higG6/lJPTOCJicP0Z8pwRP4I5xpbbhLxRNojEXrYocxb7PzZfSoj
ZnHNsospLN4ssPYBrhlHhGVL6er25vBEbyKGszT7Xx7907oMKw==
---- END SSH2 PUBLIC KEY ----

**Comment by NDKilla** [comment]
Added back to mediawiki-admin with commit f4a3ccf

**Comment by NDKilla** [comment]
The ssh key added in commit f4a3ccf is not the key I typed above?
@Southparkfan

**Comment by Southparkfan** [comment]
Fixed.
