### ISSUE TITLE
Add cp1/2 to mediawiki-admins

### ISSUE THREAD

**Issue by revi** [miraheze/puppet#42]
cp1/2 is critical to mediawiki's operations and it's directly showing mediawiki for mw1/2 (compared to db), so I think mw-admins should have access to co1/2.

**Comment by JohnFLewis** [comment]
+1 in a general idea. though I feel it'll increase the bar by requiring more knowledge. Plus sudo rules won't swap over perfectly. maybe just a cache-admins group will be better?

**Comment by NDKilla-public** [comment]
+1 for cache-admins group since we're apparently doing service specific things now? :)

**Comment by JohnFLewis** [comment]
Technically this is done now imo. It just needs people to be in the group but that's a different issue altogether - literally.
