### ISSUE TITLE
Setup backup server

### ISSUE THREAD

**Issue by labster** [miraheze/puppet#48]
Set up a server to do backups, and then backup every wiki periodically.   What do people think is a good period to repeat backups -- 1 month?  2 weeks?

**Comment by Reception123** [comment]
I think 1 month is fine and I agree we need backups.

**Comment by revi** [comment]
Daily is ideal but that's really 'ideal'.

For me, 2 weeks.

**Comment by revi** [comment]
See also miraheze/mw-config#143.

**Comment by JohnFLewis** [comment]
Frequency of backups depends completely on how you'll rotate and store long term backs, the average disk size of a backup and the disk size of the actual storage zone.

A good rule of thumb is monthly, 3 months, 6 months and 1 year (though the 1 year could be dropped because the inactivity rule if 6 months).

How you'll restore them is the interesting part. If it is a manual process - compressing would save a lot of disk space but make it more tedious. on the other hand, automatic is an entirely new design area you'd need to look at.

**Comment by NDKilla** [comment]
per my comment on miraheze/mw-config#143 I'd like to know if there's any updates on this. Automating the process would be nice and I'd like to implement it in other (non-miraheze) environments.

Backup scripts could be run automatically of course, but I (personally) don't know how to manage rotation/deletion of backups.

**Comment by labster** [comment]
https://news.ycombinator.com/item?id=11036554 "Today DigitalOcean lost our entire server"

Glad we're not on DO; they sure put the drop in Droplet.

**Comment by Southparkfan** [comment]
I don't really have an idea how to actually design a backup system with cronjobs and such.

Current way of avoiding Miraheze going up into flames (as in compromising our VPSs, our host shutting down all the things, a RAID controller failure, NLSVZS1 burning down, some random guy literally going to steal the node, the misusage of root, @Southparkfan being a jerk (no :)), etc) is by manually backupping all dbs and transferring them to somewhere.

We should really get a good backup scheme, and disaster recovery plans.

**Comment by JohnFLewis** [comment]
I think we're trying to overcomplicate a fairly simple back up idea. Ignore XML dumps as a backup strategy totally - they're user facing and can be handled case by case or by a script in the future. They're not backups that we'd use or that we'll be interested in.

We can back up everything we need via the file system and we can restore everything we need via the file system. We don't need to turn bits into useful and meaningful pieces of data to consider them a back up.

Taking a leaf from the WMF's book, Bacula is a nice piece of software that can work well and as such I'd propose this solution if we want any real solution to this problem at all.

**Comment by JohnFLewis** [comment]
We've got the details of this now sorted out. A 250GB storage server at backupsy running bacula is how we'll do it.

I'm going to be responsible for setting this up and its initial deployment.

**Comment by JohnFLewis** [comment]
I have the bulk of the module done in my local repo. It's not committed as it breaks general puppet conventions, is very very messy and include passwords (don't worry! these are throw-away able and will be changed before deploy as there will be a lot and they'll all be in private git and template by magic and universal! where as now bacula1 has like 3 different passwords and parsoid1 has 2. I'm **stopping** the services on the servers).

Please **don't** touch bacula1.

**Comment by JohnFLewis** [comment]
Helpful: A list of directories we want backed up, retention lengths etc. in the form of:
$server:$dir and then a comment on retention lengths. Up to it @Southparkfan?

**Comment by Southparkfan** [comment]
cp1:/srv/mediawiki-static # 42 days (delete oldest after 4th backup has been made), backup each 14 days
db1:/srv/mariadb # 42 days (delete oldest after 3rd backup has been made), backup each 14 days
misc1:/home/git # 90 days, backup each 7 days
misc1:/var/lib/ganglia # 1 month, backup each 7 days
mw1:/root/acme-tiny # 1 month, backup each 7 days

It should also backup all mailboxes @ misc1, but I'm not sure how to do that.

**Comment by JohnFLewis** [comment]
Eh mail-backups are not something I feel like we should be doing. If some email is important, it should be somewhere else or backed up locally. Nothing major should be lost because mail.

Rest looks good. Thanks.

**Comment by JohnFLewis** [comment]
At last this is done.
