### ISSUE TITLE
Puppetize Math extension stuff

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#5]
Current way of doing things:
sudo apt-get install texlive-latex-extra build-essential ocaml dvipng texlive-fonts-recommended texlive-latex-recommended
cd /srv/mediawiki/w/extensions/Math && sudo make

Installing "mediawiki-math-texvc" seems better to me, however: 
```
The following NEW packages will be installed:
  fonts-ipaexfont-gothic fonts-ipaexfont-mincho fonts-ipafont-gothic
  fonts-ipafont-mincho latex-cjk-all latex-cjk-chinese
  latex-cjk-chinese-arphic-bkai00mp latex-cjk-chinese-arphic-bsmi00lp
  latex-cjk-chinese-arphic-gbsn00lp latex-cjk-chinese-arphic-gkai00mp
  latex-cjk-common latex-cjk-japanese latex-cjk-japanese-wadalab
  latex-cjk-korean latex-cjk-thai libaio1 libdbd-mysql-perl libdbi-perl
  libhtml-template-perl libjs-jquery-cookie libjs-jquery-form
  libjs-jquery-tipsy libterm-readkey-perl mediawiki mediawiki-classes
  mediawiki-extensions-base mediawiki-extensions-math mediawiki-math-texvc
  mysql-client-5.5 mysql-server mysql-server-5.5 mysql-server-core-5.5
  php-wikidiff2 swath texlive-lang-chinese texlive-lang-cjk
  texlive-lang-japanese texlive-lang-korean texlive-lang-other
```
We don't want it to install mediawiki and mysql packages...

**Comment by JohnFLewis** [comment]
Seems incredibly weird for a full install. The mediawiki page seems to show it can be a simple require install with perhaps a package of so.

**Comment by Southparkfan** [comment]
It says "mediawiki-math-texvc" is enough? Well yeah, if it wouldn't install mysql* and mediawiki/mediawiki-classes/mediawiki-extensions-base.... I'd use it.

**Comment by Southparkfan** [comment]
@JohnFLewis: http://askubuntu.com/questions/179060/how-not-to-install-recommended-and-suggested-packages seems to be the solution for this. Can we somehow manage a conf file for apt in puppet?

**Comment by JohnFLewis** [comment]
--no-install-recommends is the only realistic option.

**Comment by Southparkfan** [comment]
Done in b413c8e3601bde3cffc3bce4d825463eb0db230d.
