### ISSUE TITLE
Access request: database-roots and mediawiki-roots for ndkilla

### ISSUE THREAD

**Issue by NDKilla** [miraheze/puppet#63]
Hello @miraheze/operations 
I'm a current mediawiki-admin who's been getting more and more active after a period of inactivity.
I'd like to request "roots" access on all mediawiki and database servers (currently only one of each in production iirc)

Roots access on mw1/mediawiki servers would allow me to manage the server more closely. I could avoid a lot of tedious things like running every script as -u www-data and I could manually git pull certain things from the repo without having to run all of puppet.

Roots access on db1/database servers would allow me to perform database queries there instead of using `sudo -u www-data php maintenance/sql.php` on mw1. It would also give me more access allowing me to drop actual databases after deleting a wiki in the mediawiki software.

If this is approved either my current ssh key could be used or if required I can generate a new one when I get home. As always I try to practice online security.

Welcome to any questions or concerns regarding access or usage

**Comment by JohnFLewis** [comment]
"I could avoid a lot of tedious things like running every script as -u www-data" 
Technically this is how it should be done, even by roots.

"and I could manually git pull certain things from the repo without having to run all of puppet."
This is also how it should be done.

**Comment by NDKilla** [comment]
@JohnFLewis I honestly wasn't sure about the mw1 sudo usage, so thanks for the comment.

In regards to the second part, SPF actually mentioned that. I try to avoid server-side hacking of files completely (I've never done it on mw1 even though I'm pretty sure I could do something like `sudo -u www-data nano LocalSettings.php`), so if I make a very small config change on GH I could update the settingsfile without the "overhead" of completely running puppet and waiting for it all to finish. I'd of course have to be careful not to like, update the LocalSettings/LocalExtensions.php files without pulling miraheze/mediawiki if there's updates to that.

**Comment by Southparkfan** [comment]
While it's not an official comment yet, I think you're better off with mediawiki-roots now (or something else that allows /usr/bin/git pull). Obviously root access is very powerful :)

**Comment by JohnFLewis** [comment]
I don't object to service-specific root.

**Comment by Southparkfan** [comment]
@JohnFLewis can I assume you don't object full root for NDKilla on mw*?

**Comment by JohnFLewis** [comment]
Yes you can.

**Comment by Southparkfan** [comment]
Good. No objections here either so approved.
