### ISSUE TITLE
GDNSD should not crash upon reload if config contains syntax errors

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#64]
Exactly what it says in the title. We should do more checking before we actually deploy config in production.

**Comment by JohnFLewis** [comment]
This is really QA rather than any puppet work (or upstream for GDNSD config caching but... arguments either way of this matter).

**Comment by JohnFLewis** [comment]
9787ce1e4279020bec75f941258a76d27e48adfb
