### ISSUE TITLE
NFS stuff that needs puppetizing

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#72]
I had to run exportfs -a on cp1 before it would allow me to mount on mw1, and I had to mount manually on mw1, because Puppet tried to run "mount /mnt/mediawiki-static".

**Comment by JohnFLewis** [comment]
This is already done. When exports is changed, the nfs server is restarted which catches the changes.

**Comment by Southparkfan** [comment]
I still had to mount manually though..

**Comment by JohnFLewis** [comment]
Did you run puppet after fixing the export issue?

**Comment by Southparkfan** [comment]
I ran puppet after RamNode enables NFS, returned errors. Ran puppet apply with -dtv, couldn't get interesting information ("wrong options given"). Manually ran mount -t nfs cp1ip:/srv/mediawiki-static /mnt/mediawiki-static, permission denied. Ran exportfs -a on cp1, all fixed.

You can re-install mw2 if you want and test.

**Comment by JohnFLewis** [comment]
To allow a benefit of doubt (and also a general nice test), I'll reinstall mw2 and see.

**Comment by JohnFLewis** [comment]
It was missing an options line. Fixed now.
