### ISSUE TITLE
Install dsh for multi-server management

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#74]
Should be as easy as installing dsh on all servers, and creating a file with all IPs of the servers in a particular group for each group (dns, mediawiki, etc).

**Comment by JohnFLewis** [comment]
Would require key forwarding (which is not recommended).

**Comment by Southparkfan** [comment]
@JohnFLewis do you have another proposal? It would not be too rare for me to do something on a group of servers simultaneously.

**Comment by JohnFLewis** [comment]
I don't but it is either technically impossible or possible with ignoring security standards. I had dsh installed locally and did it that way from my machine.

**Comment by Southparkfan** [comment]
What about https://wiki.archlinux.org/index.php/Saltstack?

**Comment by JohnFLewis** [comment]
Possibly but as far as I know  its heavily developed into a master-node system. Locally running dsh is best Imho or just running ssh continuously for commands (DNS restarts for me).

**Comment by JohnFLewis** [comment]
SPF has stepped away from the plate, I see no use so closing this (mostly because I have this locally and he's developed a script to do it locally. Any future root members, feel free!)
