### ISSUE TITLE
Add a plugins directory for icinga

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#86]
Icinga is a bit JohnFLewis' property, so I guess he can do it if I forget to do so.

I want to be able to add custom plugins like https://github.com/admingeekz/nagios-varnish/blob/master/check_varnishbackends.py.

**Comment by JohnFLewis** [comment]
Just file stanza it into the plugins directory (I think /usr/lib/nagios/plugins) and define it as a command. Nothing complicated really.

**Comment by Southparkfan** [comment]
Done.
