### ISSUE TITLE
Audit SSL certificates expiration

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#89]
- [x] allthetropes.org - expires 18 March 2016
- [ ] *.miraheze.org - expires 22 July 2016
- [ ] spiral.wiki - expires 3 August 2016
- [ ] anuwiki.com - expires 31 August 2016
- [ ] antiguabarbudacalypso.com - expires 14 September 2016
- [ ] permanentfuturelab.wiki - expires 20 September 2016
- [ ] secure.reviwiki.info - expires 27 September 2016
- [ ] wiki.printmaking.be - expires 29 September 2016
- [ ] private.revi.wiki - expires 3 December 2016
- [ ] oneagencydunedin.wiki - expires 27 December 2016
- [ ] publictestwiki.com - expires 8 January 2017
- [ ] boulderwiki.org - expires 14 February 2017
- [ ] wiki.zepaltusproject.com - expires 16 February 2017

allthetropes.org: needs action from my side.
*.miraheze.org: @JohnFLewis, can you share the GlobalSign account credentials with Miraheze Operations?

**Comment by JohnFLewis** [comment]
Audit in what way? This seems likes a losing battle as we put the responsibility to the users, it means the control we have is literally null.

Share? No as they're private account based. I can create accounts part of the master account though (and I thought I made you one already?)

**Comment by Southparkfan** [comment]
1: we want to warn users when they cers are going to expire.

2: no, you didn't yet.

**Comment by JohnFLewis** [comment]
1: also a losing battle in the long run I guess, mostly for a reliable way to track them which you'll know of.

2. I will today then.

**Comment by JohnFLewis** [comment]
Account is done. (just a public note)

**Comment by Southparkfan** [comment]
@labster @Arcane21:

Let's Encrypt is a pain in the ass now. I want to avoid downtime as much as possible, but I'm afraid I have to schedule a downtime for ATT in order to renew the cert...

**Comment by revi** [comment]
I thought most CA will send email when their cert are expiring soon (I have no cert expiring so IDK) so that should be sufficient. (If the wiki owners are receiving emails)

**Comment by JohnFLewis** [comment]
That's sort of the issue. They get the emails, we don't. An unsecured SSL cert does not but cause havoc for us.

**Comment by labster** [comment]
In terms of LetsEncrypt clients, here's a fragment of discussion from HN that might have some useful links:
https://news.ycombinator.com/item?id=11245250

**Comment by JohnFLewis** [comment]
Hm, still what's the objective of this issue? Surely an issue that never closes is not useful. Unless there is real objective, close this and move it to a trackable place like on-wiki or so.

**Comment by revi** [comment]
Maybe make a process of something like quarterly expiration audit by Jan/Apr/Jul/Oct (and notify the respective wiki owners) and close this issue for now?

**Comment by Southparkfan** [comment]
https://meta.miraheze.org/wiki/User:Southparkfan/tmp
