### ISSUE TITLE
Installing security updates?

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#9]
How should we install security updates? 
```
apt-get update && apt-get -s upgrade | grep "^Inst" | grep -i "security" | awk '{print $2}'
``` 
(based on http://askubuntu.com/a/217999)
gives a list of packages with available security updates, but there's still no way of automatically upgrading packages with security updates ONLY..

**Comment by addshore** [comment]
http://askubuntu.com/questions/194/how-can-i-install-just-security-updates-from-the-command-line

**Comment by JohnFLewis** [comment]
900fbdbfefb9bbf9e4a3f09755b888c341282a13

Ran on parsoid1 and db1 with no issues.
