### ISSUE TITLE
Renew allthetropes.org cert

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#93]
@labster @Arcane21:

Let's Encrypt is a pain in the ass now. I want to avoid downtime as much as possible, but I'm afraid I have to schedule a downtime for ATT in order to renew the cert...

**Comment by JohnFLewis** [comment]
I'm unfamiliar with how exactly LetsEncrypt work so I'm interested in why there have to be a 'downtime'?

That seems rather interesting as a general SSL cert renew/install doesn't result in a downtimr if handled in an order. But from my little knowledge, LE is far from a normal provider at all.

**Comment by Southparkfan** [comment]
Only ways of proving you are the owner of a domain is via HTTP requests.

cp2 (if the Let's Encrypt servers use that server at all - they can also be located in Europe, who knows...) is not the ideal place to install Let's Encrypt.

Let's Encrypt wants to run its own webserver for validation. This means I had to shutdown NGINX on my own server before it could validate allthetropes.org (yes, I pointed the domain to my server just before I switched custom domains for ATT).

There is a --webroot mode you can use so it adds files to your webroot for validation [does not require shutting down your webserver], but it failed for my own domain with the error 'invalid JSON'.

I managed to get three different versions of my own certificate, just because working with the Let's Encrypt auto script sucks. Oh and now I hit the rate limit of 5 certs per week, and I managed to delete my older certs, so I have to wait.

It sucks. This really sucks, and I have no idea how to renew a stupid cert.

**Comment by JohnFLewis** [comment]
Duly noted. Yes it does suck but is out of our control, just wanted background information.

**Comment by labster** [comment]
Is this helpful? https://community.letsencrypt.org/t/auto-renewal-with-nginx-without-downtime/7814

If not, can you post your rant on their forums?

**Comment by Southparkfan** [comment]
We don't have much time left, this is an Unbreak Now!

Will look asap at home.

**Comment by JohnFLewis** [comment]
The fix is getting LE to work on a cache proxy otherwise it's bad hacks which does not solve the problem as LE will slowly become more popular as a certificate authority.

**Comment by Southparkfan** [comment]
Puppetization is preferred, passing all LE traffic to mw* via Varnish allows us to use one host independent of cache proxy location.

**Comment by JohnFLewis** [comment]
Works for me.

**Comment by JohnFLewis** [comment]
SPF did this.
