### ISSUE TITLE
HHVM fun: add a cronjob that restarts HHVM every X hours

### ISSUE THREAD

**Issue by Southparkfan** [miraheze/puppet#95]
It is unlikely that the cause of the HHVM crashes (see #79) will ever be fixed. Since HHVM is essential in our setup, let's add a cronjob that restarts HHVM every X hours if needed.

**Comment by JohnFLewis** [comment]
As a OOM *hack*, a restart on average every 2 hours should be suitable (average life of HHVM on mw2; 4 hours. mw1; 1.5~2.5 hours)

**Comment by JohnFLewis** [comment]
bad bad hack 4049f5cab0e30ddbb974cc8f6f3f5911edc869de
